// =====================================================
// PRINTERS UAE - Customer Names
// Source: customer list.pdf
// =====================================================
export const CUSTOMERS = [
  // Section 1
  "YORK YARD",
  "YORK HQ",
  "YORK TARIF",
  "FIRST SKY",
  "Housa yousuf",
  "Starlinks",
  "Glamorous salon",
  "WORLD STAR",
  "Geo harbour 2nd",
  "Stats uk",
  "MIX DESIGN",
  "Build space",
  "Kite pro",
  "MEDI LEARN",
  "NUBSI CONTRACTING",
  "Imada",
  "Khalid Auto",
  "SPADREC",
  "Al Tareeq",
  "MARYAM Al Shamsy",
  "Creative Concepts",
  "Rise and Shine",
  "AVATAR",
  "ROCKET STATIONARY (Pencil)",
  "Impactful Minds",
  "PLUTO",
  "CC7",
  "Controls and Electrics",
  "Gulf metal",
  "Green Graphic",
  "Sprint force",
  "Ridge way",
  "Mashriq Eite",
  "Grand Fairway",
  "Shafi Ul Alam Typing",

  // Section 2
  "FUTURE INNOVATOR",
  "Practical Kitchen",
  "Al athar",
  "AIMS",
  "OiISERV",
  "Absher",
  "REALTY OLIVE TREE PROPERTIES L.L.C",
  "Start ezen",
  "Al Ishraf",
  "Laxury Gateway",
  "Al fathin",
  "sea breaze",
  "Al Tawar",
  "KNDT",
  "SERVOO",
  "SPARK INSTITUTE OF EDUCATION",
  "Royal gardens",
  "Lawnscappe",
  "Space int",
  "Bannu Gul",
  "Philie",
  "Empty SL",
  "UAE Enterprise",
  "Soluxe",
  "Fix Pro",
  "Casa Bianco",
  "Falcon energy",
  "Al ruya (burjman)",
  "Al ruya (deira)",
  "BMQ",
  "Cool Pro",
  "Apec",
  "Mix Design 2nd",
  "Grand Signature",

  // Section 3
  "Sievert",
  "RF COMBINE DISTRIBUTION - L.L.C",
  "Adroit",
  "Farooq chiller",
  "Geo harbour",
  "F2 Fzco",
  "World Star Facilities Management",
  "Teacher Resource",
  "AMIRAH",
  "NCC",
  "CECEP (plotter)",
  "Intello solutions",
  "SGWIC",
  "Casa devine",
  "Al Ramzi",
  "Frost & Sullivan",
  "Hogarth",
  "Metal Experts",
  "Dufit interiors",
  "JST Ltd",
  "Speakeasy",
  "ATIC",
  "Al Jaz (JNB)",
  "OILSERV",
  "Millennial",
  "Washoo",
  "Rehmath sha",
  "Meraki Global Energy LLC",
  "Net Express",
  "S J abed",
  "Al Zeyada",
  "Brigh tech",
  "Green secure",
  "capital control businessmen",
  "Jamal alkoon goods",
  "Bellavisa medical",

  // Section 4
  "Wild animal",
  "Ageely Entry",
  "TRANS DESERT-ENTRY OFFICE",
  "TRANS DESERT-EXIT OFFICE",
  "Shamil AL sila",
  "Shamil Al Sila",
  "White Sea",
  "Uranus",
  "Mamlakat",
  "Al Wahda",
  "Matex Clearing",
  "Al Bahar",
  "Speed Max",
  "SMS",
  "Sea Land",
  "Centro",
  "Injaz express",
  "White sea",
  "Otaz customs",
  "Trans gulf",
  "Al shola",
  "Douglas-HO (Warehouse)",
  "GIS MUTAWA",
  "Douglas-Meraam project",
  "MBASSY OF COTE D'IVOIRE-AMBASSADO",
  "EMBASSY OF COTE D'IVOIRE-MOANA",
  "EMBASSY OF COTE D'IVOIRE- HALL",
  "DOUGHLAS OHI LLC(HALL)",
  "Desertman Badazayed",
  "AAAI HR",
  "Desertman Hameem",
  "GIS Warehouse",
  "Morals MBZ",
  "AAAI Secretery",
  "GIS Mutawa (regus)",

  // Section 5
  "Douglas habshan",
  "Morais Al Raha",
  "GIS Ruwais",
  "Morais Shahama",
  "Douglas icad",
  "S200",
  "S200 Consultant",
  "S200 3rd",
  "S200 client",
  "S198",
  "S198-2nd",
  "182",
  "M16",
  "S181",
  "181 2nd",
  "S181 3rd",
  "S 188",
  "S 188 2nd",
  "S 197",
  "S 197 2nd",
  "S 197 3rd",
  "S193",
  "SITE 193-2nd",
  "Naresco Head. Accounts",
  "Naresco HQ Purchase",
  "Naresco HQ-Tender",
  "Naresco HQ Comercial",
  "Naresco HQ Contract debts",
  "S189",
  "S189 2nd",
  "S189 3rd",
  "S 189 4th",
  "S183 2nd",
  "S194",
  "S194 2nd",
  "S185",
  "S185 2nd",
  "S192",
  "S192 2nd",

  // Section 6
  "S191",
  "S191 2nd",
  "S191 3rd",
  "S191 4th",
  "S171",
  "S179",
  "S202",
  "AAAI PRO HR",
  "Douglas HO",
  "Desertman Badel",
  "Royal Classic",
  "WBG 303",
  "WBG 330",
  "WBG P328",
  "WBG HO Finance",
  "WBG 319",
  "WBG 342",
  "WBG AI Taween",
  "WBG 340",
  "WBG 336 (habshan)",
  "WBG (Main store)",
  "WBG 328 (CONSULTANT)",
  "WBG 340 (CONSULTANT)",
  "WBG 345 (CONSULTANT)",
  "WBG 330(CONSULTANT)3",
  "WBG (Motor city)",
  "WBG Mafraq store",
  "WBG 330 4TH",
  "WBG Musaffah garage",
  "WBG 340 Laydown",
  "AAAI Internal",
  "WBG 340 consultant",
  "Douglas Shuweihat",
  "Douglas Shuweihat (Supporting)",

  // Section 7
  "MORALS KHALIFA CITY",
] as const;

export type CustomerName = typeof CUSTOMERS[number];

// =====================================================
// G3 FACILITY - Customer Names (Placeholder - Update later)
// =====================================================
export const G3_CUSTOMERS = [
  "G3 Client Alpha",
  "G3 Client Beta",
  "G3 Client Gamma",
  "G3 Client Delta",
  "G3 Client Epsilon",
  "G3 Building A",
  "G3 Building B",
  "G3 Building C",
  "G3 Tower 1",
  "G3 Tower 2",
  "G3 Mall Complex",
  "G3 Office Park",
  "G3 Residential Block",
  "G3 Industrial Zone",
  "G3 Warehouse District",
] as const;

export type G3CustomerName = typeof G3_CUSTOMERS[number];

// =====================================================
// IT SERVICE - Customer Names (Placeholder - Update later)
// =====================================================
export const IT_CUSTOMERS = [
  "IT Client ABC Corp",
  "IT Client XYZ Ltd",
  "IT Client Tech Solutions",
  "IT Client Data Systems",
  "IT Client Cloud Services",
  "IT Client Network Pro",
  "IT Client Cyber Security",
  "IT Client Digital Hub",
  "IT Client Smart Office",
  "IT Client Enterprise One",
  "IT Client StartUp Inc",
  "IT Client Business Center",
  "IT Client Innovation Lab",
  "IT Client Server Farm",
  "IT Client Data Center",
] as const;

export type ITCustomerName = typeof IT_CUSTOMERS[number];
